"""new fields in user model

Revision ID: 2e1cf98af16b
Revises: 5ab762bd7043
Create Date: 2022-05-16 12:19:25.421989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1cf98af16b'
down_revision = '5ab762bd7043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.String(length=3), nullable=True))
    op.add_column('user', sa.Column('grade', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'grade')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###
