"""new fields in user model

Revision ID: 6949b17d4de2
Revises: 2e1cf98af16b
Create Date: 2022-05-16 12:25:48.219277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6949b17d4de2'
down_revision = '2e1cf98af16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('clubs_in', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('club_leader', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'club_leader')
    op.drop_column('user', 'clubs_in')
    # ### end Alembic commands ###
