"""clubs table

Revision ID: 9cfa80ec52af
Revises: 6949b17d4de2
Create Date: 2022-05-16 13:08:11.615074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfa80ec52af'
down_revision = '6949b17d4de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('leaders', sa.String(length=128), nullable=True),
    sa.Column('members', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club')
    # ### end Alembic commands ###
